#47 Получение курьера по id
MAVIKE/yad-backend pull request #51
Opened 2021-03-21 23:52 UTC by drhugoz

2021-03-21 23:53 UTC, drhugoz commented
@architectv @VolkovEgor сомневаюсь в том, у кого есть доступ к получению курьера по id

2021-03-21 23:55 UTC, drhugoz commented on internal/service/courier.go
> +	}
пока вот так сделал @architectv

2021-03-22 11:07 UTC, VolkovEgor requested changes

2021-03-22 11:07 UTC, VolkovEgor commented on internal/delivery/http/v1/courier.go
> +// @Success 200 {object} domain.Category
Должен возвращаться domain.Courier
tags должен быть couriers

2021-03-22 14:29 UTC, drhugoz commented on internal/delivery/http/v1/courier.go
> +// @Success 200 {object} domain.Category
done

2021-03-22 20:38 UTC, VolkovEgor approved these changes

2021-03-22 20:43 UTC, architectv approved these changes

2021-03-22 20:43 UTC, merged