#23 удаление блюда из заказа
MAVIKE/yad-backend pull request #52
Opened 2021-03-24 13:34 UTC by HammerFall42

Resolve #23

2021-03-24 13:35 UTC, HammerFall42 commented on internal/repository/order.go
> +	_, err := r.db.Exec(query, orderId, orderItemId)
Нужна ли здесь проверка на то, что хоть что-то удалилось?

2021-03-27 18:23 UTC, architectv commented on internal/repository/order.go
> +	_, err := r.db.Exec(query, orderId, orderItemId)
Нет, все ок

2021-03-27 18:24 UTC, architectv requested changes

2021-03-27 18:24 UTC, architectv commented on internal/service/order.go
> +func (s *OrderService) DeleteItem(clientId int, clientType string, orderId int, orderItemId int) error {
Нужно проверять, кто удаляет блюдо из заказа -- только юзер, относящийся к заказу.

2021-03-28 10:52 UTC, architectv commented on internal/service/order.go
> +func (s *OrderService) DeleteItem(clientId int, clientType string, orderId int, orderItemId int) error {
@HammerFall42

2021-03-28 11:31 UTC, architectv commented on internal/service/order.go
> +func (s *OrderService) DeleteItem(clientId int, clientType string, orderId int, orderItemId int) error {
@HammerFall42 
Можешь глянуть, как проверка осуществляется в GetById.

https://github.com/MAVIKE/yad-backend/blob/86744f17ec56b7714e74de3018a8c57629ca37f4/internal/service/order.go#L40

2021-03-28 14:39 UTC, architectv commented on internal/service/order.go
> +func (s *OrderService) DeleteItem(clientId int, clientType string, orderId int, orderItemId int) error {
Сделай git rebase, а то конфликты при слиянии будут.

2021-03-28 14:44 UTC, VolkovEgor commented on internal/service/order.go
> +func (s *OrderService) DeleteItem(clientId int, clientType string, orderId int, orderItemId int) error {
Нужно так же проверить, что orderItemId принадлежит orderId
Лучше посмотреть, как проверки реализованы в UpdateItem

https://github.com/MAVIKE/yad-backend/blob/7b7edad441a6451b8c3881f040626aca8a4d9743/internal/service/order.go#L111

2021-03-28 14:51 UTC, HammerFall42 commented on internal/service/order.go
> +func (s *OrderService) DeleteItem(clientId int, clientType string, orderId int, orderItemId int) error {
Добавил

2021-03-28 15:12 UTC, merged