#66 Редактирование курьера
MAVIKE/yad-backend pull request #77
Opened 2021-04-03 17:48 UTC by drhugoz

resolve #66

Еще есть некоторые вопросы, мержить нельзя

1. Как и что можно менять у курьера
2. Правильно ли реализовано то, что есть

2021-04-03 18:20 UTC, architectv requested changes

2021-04-03 18:20 UTC, architectv commented on internal/repository/courier.go
> +func (r *CourierPg) Update(courierId int, input *domain.Courier) error {
Посмотри, как это сделано здесь:
https://github.com/zhashkevych/todo-app/blob/4ffc4325f3c11f6dd73d55d2c0c39c15f6f97059/pkg/repository/todo_list_postgres.go#L72

https://github.com/architectv/merchantx-task/blob/8acb0f5218f2d1247de91c6604a7bd52978801be/pkg/repository/offer_postgres.go#L80

Можно также попробовать использовать эту библиотеку для упрощения построения запросов:
https://github.com/Masterminds/squirrel

2021-04-03 18:20 UTC, architectv commented on internal/service/courier.go
> +	if !(input.WorkingStatus == unable || input.WorkingStatus == waiting || input.WorkingStatus == working) {
Может быть, лучше использовать switch-case.

2021-04-03 18:27 UTC, architectv requested changes

2021-04-03 18:27 UTC, architectv commented on internal/service/courier.go
> +func (s *CourierService) Update(clientId int, clientType string, courierId int, input *domain.Courier) error {
Нет проверки на поля, которые может менять админ.
Лучше разделить сценарии на 2 if (админ/курьер).
Еще нужно добавить проверку, что у курьера нет активных заказов -- эта задача #30 еще не реализована,
можно оставить комментарий TODO, чтобы не забыть в дальнейшем -- нужно будет ходить в репозиторий и проверять активные заказы.

2021-04-03 18:27 UTC, architectv requested changes

2021-04-03 18:27 UTC, architectv commented on internal/service/service.go
> +
Комментарием лучше пояснить, чьи статусы.

2021-04-03 21:16 UTC, architectv commented on internal/service/courier.go
> +	if !(input.WorkingStatus == unable || input.WorkingStatus == waiting || input.WorkingStatus == working) {
@drhugoz 
Что-то типа такого имею в виду:
```
switch input.WorkingStatus {
case unable, waiting, working:
    break
default:
    // error
}
```
Выглядит лучше: читаемо, понятно.

2021-04-04 13:44 UTC, architectv approved these changes

2021-04-04 13:44 UTC, architectv commented
@VolkovEgor 
Проверь тоже, плиз. Важный момент.

2021-04-04 13:54 UTC, architectv requested changes

2021-04-04 13:54 UTC, architectv commented on internal/repository/courier.go
> +	// TODO : добавить поле со статусом и локацией
Так здесь так же обновлять, как и остальные поля, @drhugoz

2021-04-04 13:56 UTC, architectv requested changes

2021-04-04 13:56 UTC, architectv commented on internal/service/courier.go
> +	if !(input.WorkingStatus == unable || input.WorkingStatus == waiting || input.WorkingStatus == working) {
@drhugoz 
Где красивенький switch-case?)

2021-04-05 13:34 UTC, architectv requested changes

2021-04-05 13:34 UTC, architectv commented on internal/repository/courier.go
> +		createLocationQuery := fmt.Sprintf(
Лучше менять существующую запись в locations.
Запросы будут частыми, создавать новые записи накладно.

2021-04-05 13:34 UTC, architectv commented on internal/repository/courier.go
> +	if input.WorkingStatus >= 0 && input.WorkingStatus <= 2 {
Здесь не нужна логическая проверка.
Лучше ее сделать при создании таблицы с помощью CHECK в SQL-скрипте.

2021-04-05 13:48 UTC, VolkovEgor requested changes

2021-04-05 13:48 UTC, VolkovEgor commented on internal/service/service.go
> +	// courier status
Статусы добавил в пакет consts, лучше использовать их

2021-04-05 14:30 UTC, architectv commented
LOL линтер не прошел

2021-04-05 14:36 UTC, architectv approved these changes

2021-04-05 14:37 UTC, VolkovEgor approved these changes

2021-04-05 14:37 UTC, merged