#84 Добавление проверки на активный заказ у курьера
MAVIKE/yad-backend pull request #85
Opened 2021-04-05 21:51 UTC by drhugoz

resolve #84

2021-04-05 22:18 UTC, architectv requested changes

2021-04-05 22:18 UTC, architectv commented on internal/service/courier.go
> +		repoOrder:      repoOrder,
Лучше orderRepo, но не суть.

2021-04-05 22:18 UTC, architectv commented on internal/service/courier.go
> +	} else if err != nil && input.WorkingStatus == consts.CourierWorking {
А если err != nil, а WorkingStatus != CourierWorking?

2021-04-05 22:18 UTC, architectv commented on internal/service/courier.go
> +	} else if err != nil && input.WorkingStatus == consts.CourierWorking {
Зачем в случае ошибки проверка на работу курьера?

2021-04-05 22:40 UTC, drhugoz commented on internal/service/courier.go
> +		repoOrder:      repoOrder,
поменяю

2021-04-05 22:43 UTC, drhugoz commented on internal/service/courier.go
> +	} else if err != nil && input.WorkingStatus == consts.CourierWorking {
nil вернется в случае, если не получилось получить активный заказ у курьера. Соответственно здесь я проверяю на два ошибочных случая:
1) заказ у курьера есть (заказ получили без ошибок) и мы хотим установить курьеру статус, который подразумевает, что заказа у него уже нет
2) заказа у курьера нет (получили ошибку считывания из базы), а мы пытаемся установить ему статус, который подразумевает, что заказ у него есть

2021-04-05 22:46 UTC, drhugoz commented on internal/service/courier.go
> +	} else if err != nil && input.WorkingStatus == consts.CourierWorking {
Если err != nil, а WorkingStatus != CourierWorking, то получается ситуация, что заказа у курьера нет (ошибка считывания у базы), но мы и не хотим ставить ему статус, который подразумевает наличие заказа, поэтому выполнение просто продолжится дальше

2021-04-06 05:56 UTC, architectv approved these changes

2021-04-06 10:13 UTC, drhugoz commented
@VolkovEgor сделай ревью

2021-04-06 10:28 UTC, VolkovEgor approved these changes

2021-04-06 10:51 UTC, merged