#46 Получение пользователя по id
MAVIKE/yad-backend pull request #89
Opened 2021-04-07 23:43 UTC by drhugoz

resolve #46

2021-04-07 23:52 UTC, VolkovEgor commented on internal/service/user.go
> +	case userType:
Один пользователь может получать другого?
Вроде правильнее выглядит разрешить пользователю получать только свой профиль

2021-04-08 06:52 UTC, architectv requested changes

2021-04-08 06:52 UTC, architectv commented on internal/service/user.go
> +	case userType:
Switch-case красивый.
Юзер действительно может только сам себя получать.

2021-04-08 12:07 UTC, drhugoz commented on internal/service/user.go
> +	case userType:
done

2021-04-08 12:34 UTC, VolkovEgor approved these changes

2021-04-08 12:35 UTC, merged