#64 Удаление категории блюд для ресторана
MAVIKE/yad-backend pull request #93
Opened 2021-04-09 13:43 UTC by HammerFall42

Resolve #64

2021-04-09 19:46 UTC, VolkovEgor approved these changes

2021-04-09 19:50 UTC, architectv requested changes

2021-04-09 19:50 UTC, architectv commented on internal/repository/restaurant.go
> +	if err == sql.ErrNoRows {
Надо проверять еще случай, если err != nil.
err == sql.ErrNoRows можно внутри общей проверки на err != nil сделать.

2021-04-09 20:27 UTC, architectv commented on internal/repository/restaurant.go
> +	if err == sql.ErrNoRows {
Вообще на слое репозитория достаточно просто err пробрасывать наверх.

2021-04-10 11:21 UTC, HammerFall42 commented on internal/repository/restaurant.go
> +	if err == sql.ErrNoRows {
Исправил

2021-04-10 11:27 UTC, architectv approved these changes

2021-04-10 11:27 UTC, architectv commented on internal/repository/restaurant.go
> +		} else {
Можно было без else здесь

2021-04-10 11:28 UTC, VolkovEgor approved these changes

2021-04-10 11:28 UTC, merged